modLoader="javafml"
loaderVersion="[4,)"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
description='''A client-side resource-pack organizer.'''

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="[1.21.11,1.21.12)"
ordering="NONE"
side="CLIENT"
